// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luafalcao.api.Persistence.Contexts;

namespace luafalcao.api.Web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220822153716_Incluindo_Dados_Iniciais")]
    partial class Incluindo_Dados_Iniciais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("luafalcao.api.Persistence.Entities.Escolaridade", b =>
                {
                    b.Property<int>("EscolaridadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EscolaridadeId");

                    b.ToTable("Escolaridade");

                    b.HasData(
                        new
                        {
                            EscolaridadeId = 1,
                            Descricao = "Infantil"
                        },
                        new
                        {
                            EscolaridadeId = 2,
                            Descricao = "Fundamental"
                        },
                        new
                        {
                            EscolaridadeId = 3,
                            Descricao = "Médio"
                        },
                        new
                        {
                            EscolaridadeId = 4,
                            Descricao = "Superior"
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EscolaridadeId")
                        .HasColumnType("int");

                    b.Property<int?>("HistoricoEscolarId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EscolaridadeId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            DataNascimento = new DateTime(1990, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscolaridadeId = 2,
                            Nome = "José",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            UsuarioId = 2,
                            DataNascimento = new DateTime(1975, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscolaridadeId = 3,
                            Nome = "Julia",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            UsuarioId = 3,
                            DataNascimento = new DateTime(1968, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscolaridadeId = 4,
                            Nome = "João",
                            Sobrenome = "Silva"
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Entities.Usuario", b =>
                {
                    b.HasOne("luafalcao.api.Persistence.Entities.Escolaridade", "Escolaridade")
                        .WithMany()
                        .HasForeignKey("EscolaridadeId");
                });
#pragma warning restore 612, 618
        }
    }
}
